Repository VeryBigThings/keechma-next-web-template, pull requests merged in 2020-08, with the labels that each got.

#1 Add npx in order to run pre-commit hook properly
  .githooks/pre-commit
Labels: enhancement, release:minor

#2 Fix tooling - add missing .rc files and fix pre-commit hook
  .clj-kondo/config.edn
  .githooks/pre-commit
  .zprintrc
Labels: enhancement, release:minor

#3 Update deps.edn
  deps.edn
Labels: release:patch

#11 Fix workflows and add examples
  .github/actions/tag-and-release/Dockerfile
  .github/actions/tag-and-release/action.yml
  .github/actions/tag-and-release/bin/install_babashka.sh
  .github/actions/tag-and-release/src/release_on_push_action/core.clj
  .github/actions/tag-and-release/src/release_on_push_action/github.clj
  .github/actions/versioning/Dockerfile
  .github/actions/versioning/action.yml
  .github/actions/versioning/entrypoint.sh
  .github/workflows/versioning.yml
  README.md
Labels: bug, release:major

#12 Update workflow files
  .github/workflows/summarization.yml
  .github/workflows/versioning.yml
Labels: enhancement, release:minor

#14 Fixes and improvements
  .zprintrc
  guardrails.edn
  package.json
  shadow-cljs.edn
  src/app/app.cljs
  src/app/ui/style.css
  tailwind.config.js
Labels: release:minor

#16 Fix indent error
  .github/workflows/summarization.yml
Labels: bug, release:patch

#19 Add missing app instance reset
  src/app/core.cljs
Labels: bug, release:minor
